export default [
    {
      _id: 1,
      storeName: 'Al di la',
      address: '250 West 57th Street, New York, NY',
      zipCode: '11215',
      type: 'Food/Beverage',
      email: 'aldila@gmail.com',
      password: 'merchant1',
      description:
        'Welcome to our family-run Italian restaurant, where fresh, traditional flavors come together to form a unique dining experience. Our menu is full of classic Italian favorites like pasta, pizza, and antipasti, all made with the freshest ingredients and prepared with a modern twist. Our dishes are created with passion and love, and our cozy atmosphere will make you feel right at home. Come experience the warmth and flavor of Italy while being surrounded by family and friends.',
      image: 'https://i.imgur.com/86ek7TZ.png',
    },
    {
      _id: 2,
      storeName: 'Bagel Works',
      address: '745 5th Avenue, New York, NY',
      zipCode: '11215',
      type: 'Food/Beverage',
      email: 'bagelworks@gmail.com',
      password: 'merchant2',
      description:
        'Welcome to Bagel Works! We specialize in freshly baked bagels that are made with the highest quality ingredients. Our bagels come in a variety of flavors including everything, onion, poppy seed, cinnamon raisin, and garlic. We also offer a wide selection of spreads and toppings to make your bagel the perfect snack. Whether youre looking for a quick bite on the go or a cozy place to sit down and enjoy your breakfast, our Bagel Store has you covered. Stop by today and enjoy the freshness and deliciousness of our bagels!',
      image: 'https://i.imgur.com/SNk7OHJ.png',
    },
    {
      _id: 3,
      storeName: 'Casa Amadeo',
      address: '825 7th Avenue, New York, NY',
      zipCode: '11215',
      type: 'Retail',
      email: 'casaamadeo@gmail.com',
      password: 'merchant3',
      description:
        'Casa Amadeo is a premier online store offering the best selection of Latin music in the world! We offer a wide variety of albums, singles, compilations and more from both classic and modern Latin music genres. Our collection features albums from salsa, bachata, merengue, cumbia, reggaeton and more. Our team of music experts have hand-selected each album to ensure the best listening experience for our customers. Stop by Casa Amadeo for the ultimate Latin music experience!',
      image: 'https://i.imgur.com/HETHCkU.png',
    },
    {
      _id: 4,
      storeName: 'Bird',
      address: '1776 Broadway, New York, NY',
      zipCode: '11215',
      type: 'Retail',
      email: 'bird@gmail.com',
      password: 'merchant4',
      description:
        'Welcome to Bird clothing store! We carry the latest trends in mens, womens and childrens fashion at affordable prices. Our selection includes everything from casual apparel and everyday basics to formalwear and special occasion outfits. We also offer a wide range of accessories including shoes, bags, sunglasses, and jewelry. Our friendly staff is here to help you find the perfect piece for any occasion. Stop by and check us out!',
      image: 'https://i.imgur.com/5tBMIEK.png',
    },
    {
      _id: 5,
      storeName: 'Lucien',
      address: '521 West 21st Street, New York, NY',
      zipCode: '11215',
      type: 'Food/Beverage',
      email: 'lucien@gmail.com',
      password: 'merchant5',
      description:
        'Lucien is an upscale French restaurant located in the heart of the city. The restaurant offers an array of classic French dishes, ranging from traditional favorites such as steak frites and moules mariniere to more creative and inventive options. The atmosphere is elegant and refined, making Lucien an ideal choice for a romantic dinner or a special occasion. The staff is friendly and attentive, and they are always happy to help guests with menu selections. With its delicious food and warm atmosphere, Lucien is a great spot to enjoy a truly special dining experience.',
      image: 'https://i.imgur.com/BvEXyTr.png',
    },
    {
      _id: 6,
      storeName: 'Palma',
      address: '250 West 57th Street, New York, NY',
      zipCode: '11215',
      type: 'Food/Beverage',
      email: 'palma@gmail.com',
      password: 'merchant6',
      description:
        'Palma is a cozy Mediterranean restaurant located in the heart of downtown. The restaurant has a warm and inviting atmosphere, with exposed brick walls, dark wood floors, and warm lighting. The menu features freshly made dishes from classic Mediterranean cuisine, including a variety of tapas, homemade pastas, and wood-fired pizzas. The restaurant also has an extensive wine list, with a selection of wines from around the world. With its inviting atmosphere, delicious food, and excellent service, Palma is the perfect spot for a romantic dinner or a gathering with friends.',
      image: 'https://i.imgur.com/9b4IyjU.png',
    },
    {
      _id: 7,
      storeName: 'Rays Candy Store',
      address: '250 West 57th Street, New York, NY',
      zipCode: '11215',
      type: 'Food/Beverage',
      email: 'rayscandystore@gmail.com',
      password: 'merchant7',
      description:
        'Welcome to Rays Candy Store! Our shop is filled with an array of delicious treats to satisfy your sweet tooth. We carry a wide selection of classic and modern candies, from gummy bears to sour belts, and everything in between. We also have a variety of unique and international treats to explore, as well as sugar-free options. Our staff is friendly and knowledgeable, and always happy to help you find the perfect candy. Stop by today and let us take care of your sweet tooth cravings.',
      image: 'https://i.imgur.com/EPco0j9.png',
    },
    {
      _id: 8,
      storeName: 'Russ & Daughters',
      address: '845 United Nations Plaza, New York, NY',
      zipCode: '10065',
      type: 'Food/Beverage',
      email: 'russanddaughters@gmail.com',
      password: 'merchant8',
      description:
        'Russ & Daughters is an iconic New York City landmark and a beloved purveyor of smoked fish, caviar, herrings, Jewish specialties, and traditional appetizing foods. Founded in 1914 by Polish immigrants Joel Russ and his daughter Anne, the store has been operated by four generations of the family since then. Located in the historic Lower East Side of Manhattan, the store is renowned for its selection of smoked fish, including salmon, sturgeon, whitefish, chubs, and more. It also offers a variety of herring, pickles, and other old-school New York specialties. In addition to its traditional offerings, Russ & Daughters also carries a selection of gourmet items, including cheeses, chocolates, and other treats',
      image: 'https://i.imgur.com/Ci3lhtC.png',
    },
    {
      _id: 9,
      storeName: 'Zuzus Petal',
      address: '33 Beekman Street, New York, NY',
      zipCode: '10065',
      type: 'Retail',
      email: 'zuzus@gmail.com',
      password: 'merchant9',
      description:
        'Welcome to our flower shop! We specialize in providing beautiful and unique floral arrangements for any occasion. Our professionally trained florists create unique, custom-made arrangements with fresh and vibrant flowers. We offer a large selection of seasonal and exotic blooms, as well as a variety of plant and gift options. We also provide delivery services to ensure your order is quickly and safely delivered. Whether you need a special bouquet for a birthday or a stunning centerpiece for a wedding, we can help you create the perfect floral arrangement. Shop with us today and experience the beauty and freshness of our blooms!',
      image: 'https://i.imgur.com/LSAHHRK.png',
    },
  ];
  